version: '2'


services:
    hubdoc:
        image: hubdoc:3.4.0
        container_name: "hubdoc"
        ports:
         - "9999:8080"
        networks:
         - onprem
    hub:
        image: hub:3.4.0
        container_name: "hub.bds-ad.lc"
        ports:
         - "4181"
         - "8080:8080"
         - "7081:7081"
         - "55436"
         - "8009"
         - "8993"
         - "8909"
        networks:
         - onprem
        volumes:
         - hub_db_data:/var/lib/blckdck/hub:rw
         - hub_lic_data:/opt/blackduck/hub/config:rw
        hostname:  "hub.bds-ad.lc" 
volumes:
  hub_db_data:
    driver: local
  hub_lic_data:
    driver: local
networks:
    hub:

